import { PathContextProvider } from '../contexts/pathContext'
import styles from '../styles/Layout.module.scss'
import { useState } from 'react'
import TopArea from './TopArea';
import Head from 'next/head'

function Layout({ children }) {
    const [globalPath, setGlobalPath] = useState([]);

    return (
        <PathContextProvider values={{ globalPath, setGlobalPath }}>
            <Head>
                <title>Breadcrumbs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.mainContainer}>
                <TopArea></TopArea>
                <div className={styles.displayContainer}>
                    {children}
                </div>
            </div>
        </PathContextProvider>
    )
}

export default Layout